export const actions = {
    OPEN_GRAPH_CLASS_LIST:  'OPEN_GRAPH_CLASS_LIST',
    GET_ALL_GRADES:         'GET_ALL_GRADES',
    DISPLAY_SUBJECT_GRADES: 'DISPLAY_SUBJECT_GRADES',
    DISPLAY_EXAM_GRADES:    'DISPLAY_EXAM_GRADES',
    GET_ALL_EXAMS:          'GET_ALL_EXAMS'
};
