export const HANDLE_SCHOOL_DATA = 'HANDLE_SCHOOL_DATA'
export const DISPLAY_SCHOOL_DATA = 'DISPLAY_SCHOOL_DATA'

export const CHANGE_CLASSROOM_TAB = 'CHANGE_CLASSROOM_TAB'
export const ADD_CLASSROOM_DATA = 'ADD_CLASSROOM_DATA'
export const GET_CLASSROOM_DATA = 'GET_CLASSROOM_DATA'

export const DISPLAY_ROOM_MODAL = 'DISPLAY_ROOM_MODAL'
export const UPDATE_CLASSROOM = 'UPDATE_CLASSROOM'

export const UPDATE_CLASS_LIST = 'UPDATE_CLASS_LIST'
export const GET_SINGLE_SUBJECT = 'GET_SINGLE_SUBJECT'
export const ADD_NEW_SUBJECT = 'ADD_NEW_SUBJECT'
export const GET_SUBJECT_LIST = 'GET_SUBJECT_LIST'
export const DISPLAY_SUBJECT_MODAL = 'DISPLAY_SUBJECT_MODAL'
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT'
