export const actions = {
	ADD_NEW_STUDENT: 'ADD_NEW_STUDENT',
	GET_ALL_STUDENTS: 'GET_ALL_STUDENTS',
	GET_SINGLE_STUDENT: 'GET_SINGLE_STUDENT',
	DISPLAY_STUDENT_GRAPH: 'DISPLAY_STUDENT_GRAPH',
	DISPLAY_STUDENT_SUBJECT_GRAPH: 'DISPLAY_STUDENT_SUBJECT_GRAPH',
	STUDENT_FORM_VALIDATION: 'STUDENT_FORM_VALIDATION',
	STUDENT_MODAL_VALIDATION: 'STUDENT_MODAL_VALIDATION'
}
