export const actions = {
	GET_ALL_NOTES: 'GET_ALL_NOTES',
	OPEN_STUDENT_NOTES_DROPDOWN: 'OPEN_STUDENT_NOTES_DROPDOWN',
	OPEN_NOTES_DROPDOWN: 'OPEN_NOTES_DROPDOWN',
	UPDATE_TEXTAREA: 'UPDATE_TEXTAREA',
	UPDATE_TITLE: 'UPDATE_TITLE',
	CLEAR_NOTE_FIELDS: 'CLEAR_NOTE_FIELDS',
	UPDATE_NOTE: 'UPDATE_NOTE',
	NOTES_FORM_VALIDATION: 'NOTES_FORM_VALIDATION'
}
