export const UPDATE_GRADING_DATA = 'UPDATE_GRADING_DATA'
export const GET_SYSTEM_TYPE = 'GET_SYSTEM_TYPE'
export const HANDLE_SCHOOL_DATA = 'HANDLE_SCHOOL_DATA'
export const DISPLAY_SCHOOL_DATA = 'DISPLAY_SCHOOL_DATA'
