export const actions = {
    SHOW_ADD_DIALOG: 'SHOW_ADD_DIALOG',
    GET_ALL_EVENTS:  'GET_ALL_EVENTS',
    CLOSE_DIALOG:    'CLOSE_DIALOG',
    ADD_EVENT:       'ADD_EVENT',
    DELETE_EVENT:    'DELETE_EVENT'
};
