export const HANDLE_SCHOOL_DATA = 'HANDLE_SCHOOL_DATA'
export const DISPLAY_SCHOOL_DATA = 'DISPLAY_SCHOOL_DATA'

export const CHANGE_CLASSROOM_TAB = 'CHANGE_CLASSROOM_TAB'
export const ADD_CLASSROOM_DATA = 'ADD_CLASSROOM_DATA'
export const GET_CLASSROOM_DATA = 'GET_CLASSROOM_DATA'

export const OPEN_CLOSE_ROOM_MODAL = 'OPEN_CLOSE_ROOM_MODAL'
export const UPDATE_CLASSROOM = 'UPDATE_CLASSROOM'

export const UPDATE_CLASS_LIST = 'UPDATE_CLASS_LIST'
export const GET_SINGLE_SUBJECT = 'GET_SINGLE_SUBJECT'
export const ADD_NEW_SUBJECT = 'ADD_NEW_SUBJECT'
export const GET_SUBJECT_LIST = 'GET_SUBJECT_LIST'
export const OPEN_CLOSE_SUBJECT_MODAL = 'OPEN_CLOSE_SUBJECT_MODAL'
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT'

export const ADD_NEW_EXAM = 'ADD_NEW_EXAM'
export const GET_SELECTED_CLASS = 'GET_SELECTED_CLASS'
export const UPDATE_DROPDOWN_CLASS_LIST = 'UPDATE_DROPDOWN_CLASS_LIST'
export const DISPLAY_SUBJECT_LIST = 'DISPLAY_SUBJECT_LIST'
export const GET_SINGLE_EXAM = 'GET_SINGLE_EXAM'
export const UPDATE_EXAMS_LIST = 'UPDATE_EXAMS_LIST'

export const ADD_NEW_STUDENT = 'ADD_NEW_STUDENT'
export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS'
export const GET_SINGLE_STUDENT = 'GET_SINGLE_STUDENT'
export const DISPLAY_STUDENT_GRAPH = 'DISPLAY_STUDENT_GRAPH'
export const DISPLAY_STUDENT_SUBJECT_GRAPH = 'DISPLAY_STUDENT_SUBJECT_GRAPH'

export const DISPLAY_EXAM_TABLE = 'DISPLAY_EXAM_TABLE'
export const OPEN_CLASS_LIST = 'OPEN_CLASS_LIST'
export const UPDATE_EXAM_TABLE = 'UPDATE_EXAM_TABLE'

export const HANDLE_MENU_CHANGE = 'HANDLE_MENU_CHANGE'

export const OPEN_GRAPH_CLASS_LIST = 'OPEN_GRAPH_CLASS_LIST'
export const GET_ALL_GRADES = 'GET_ALL_GRADES'
export const DISPLAY_SUBJECT_GRADES = 'DISPLAY_SUBJECT_GRADES'
export const DISPLAY_EXAM_GRADES = 'DISPLAY_EXAM_GRADES'
export const GET_ALL_EXAMS = 'GET_ALL_EXAMS'

export const UPDATE_GRADING_DATA = 'UPDATE_GRADING_DATA'
export const GET_SYSTEM_TYPE = 'GET_SYSTEM_TYPE'

export const GET_ALL_NOTES = 'GET_ALL_NOTES'
export const OPEN_STUDENT_NOTES_DROPDOWN = 'OPEN_STUDENT_NOTES_DROPDOWN'
export const OPEN_NOTES_DROPDOWN = 'OPEN_NOTES_DROPDOWN'
export const UPDATE_TEXTAREA = 'UPDATE_TEXTAREA'
export const UPDATE_TITLE = 'UPDATE_TITLE'
export const CLEAR_NOTE_FIELDS = 'CLEAR_NOTE_FIELDS'
export const UPDATE_NOTE = 'UPDATE_NOTE'

export const OPEN_CLOSE_CLASS_LIST = 'OPEN_CLOSE_CLASS_LIST'
export const OPEN_CLOSE_SUBJECT_LIST = 'OPEN_CLOSE_SUBJECT_LIST'
