export const actions = {
    UPDATE_CLASS_LIST:        'UPDATE_CLASS_LIST',
    GET_SINGLE_SUBJECT:       'GET_SINGLE_SUBJECT',
    ADD_NEW_SUBJECT:          'ADD_NEW_SUBJECT',
    GET_SUBJECT_LIST:         'GET_SUBJECT_LIST',
    OPEN_CLOSE_SUBJECT_MODAL: 'OPEN_CLOSE_SUBJECT_MODAL',
    UPDATE_SUBJECT:           'UPDATE_SUBJECT',
    SUBJECT_FORM_VALIDATION:  'SUBJECT_FORM_VALIDATION',
    SUBJECT_MODAL_VALIDATION: 'SUBJECT_MODAL_VALIDATION'
};
