export const CHANGE_CLASSROOM_TAB = 'CHANGE_CLASSROOM_TAB'
export const ADD_CLASSROOM_DATA = 'ADD_CLASSROOM_DATA'
export const GET_CLASSROOM_DATA = 'GET_CLASSROOM_DATA'
export const UPDATE_CLASSROOM = 'UPDATE_CLASSROOM'
export const OPEN_CLOSE_ROOM_MODAL = 'OPEN_CLOSE_ROOM_MODAL'
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT'
export const CLASSROOM_FORM_VALIDATION = 'CLASSROOM_FORM_VALIDATION'
export const CLASSROOM_MODAL_VALIDATION = 'CLASSROOM_MODAL_VALIDATION'

export const actions = {
	CHANGE_CLASSROOM_TAB: 'CHANGE_CLASSROOM_TAB',
	ADD_CLASSROOM_DATA: 'ADD_CLASSROOM_DATA',
	GET_CLASSROOM_DATA: 'GET_CLASSROOM_DATA',
	UPDATE_CLASSROOM: 'UPDATE_CLASSROOM',
	OPEN_CLOSE_ROOM_MODAL: 'OPEN_CLOSE_ROOM_MODAL',
	UPDATE_SUBJECT: 'UPDATE_SUBJECT',
	CLASSROOM_FORM_VALIDATION: 'CLASSROOM_FORM_VALIDATION',
	CLASSROOM_MODAL_VALIDATION: 'CLASSROOM_MODAL_VALIDATION'
}
