export const actions = {
    GET_SELECTED_CLASS:         'GET_SELECTED_CLASS',
    ADD_NEW_EXAM:               'ADD_NEW_EXAM',
    UPDATE_DROPDOWN_CLASS_LIST: 'UPDATE_DROPDOWN_CLASS_LIST',
    DISPLAY_SUBJECT_LIST:       'DISPLAY_SUBJECT_LIST',
    GET_SINGLE_EXAM:            'GET_SINGLE_EXAM',
    UPDATE_EXAMS_LIST:          'UPDATE_EXAMS_LIST',
    EXAM_FORM_VALIDATION:       'EXAM_FORM_VALIDATION',
    EXAM_MODAL_VALIDATION:      'EXAM_MODAL_VALIDATION'
};
